google-java-format.version=1.35.0
google-java-format.source=https://central.sonatype.com/artifact/com.google.googlejavaformat/google-java-format/1.35.0
node.version=24.15.0
node.source=https://nodejs.org/dist/v24.15.0/
shfmt.version=3.13.1
shfmt.source=https://github.com/mvdan/sh/releases/tag/v3.13.1
prettier.version=3.6.2
prettier.source=https://www.npmjs.com/package/prettier/v/3.6.2
sql-formatter.version=15.7.3
sql-formatter.source=https://www.npmjs.com/package/sql-formatter/v/15.7.3
perltidy.version=20260204
perltidy.source=https://metacpan.org/dist/Perl-Tidy/view/lib/Perl/Tidy.pod
